FROM java:8
MAINTAINER lizhiguo
VOLUME /tmp
COPY target/bandian-0.0.1-SNAPSHOT.jar bandian-js.jar
RUN bash -c 'touch /bandian-js.jar'
EXPOSE 8003
ENTRYPOINT ["java","-jar","bandian-js.jar","--server.port=8003","--spring.profiles.active=prod","--Xms1024m -Xmx1024m  -XX:PermSize=512m -XX:MaxPermSize=512m"]