bandian:
  excleUploadPath: excle
  isSingleLogin: false #true 同一个账号只能登陆一次，false 同一个账号可以多处同时登陆
  prefixPath: attach
  appraisePath: appraise # 审核文档生成路径
  limitSubmit: 0 #限制总提交次数 0为不限制  eg: 2 代表允许用户首次提交+修改一次
  name: bandian
  version: 1.0
  email: 530068684@qq.com
  url:
server:
  shutdown: graceful #开启优雅停机，默认是立即停机IMMEDIATE
spring:
  output.ansi.enabled: always
  profiles:
    active: dev #dev--本地开发环境；sit--测试环境；uat--准生产环境；prod--生产环境；
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌有效期（12小时 12 * 60 * 60 * 1000）
  expireTime: 43200000
    #mybatis-plus:
    #  Configuration:
    #    mapUnderscoreToCamelCase: true #是否开启自动驼峰命名规则
    #    callSettersOnNulls: true # 默认值：false 指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法，通常运用于有 Map.keySet() 依赖或 null 值初始化的情况。
    #  DbConfig:
    #    idType: ID_WORKER
    #logicDeleteValue: 1 #逻辑已删除值  类型string 默认值1
  #logicNotDeleteValue #逻辑未删除值 默认值 0

mybatis-plus:
#  Configuration:
#    mapUnderscoreToCamelCase: true #是否开启自动驼峰命名规则
#    callSettersOnNulls: true # 默认值：false 指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法，通常运用于有 Map.keySet() 依赖或 null 值初始化的情况。
  mapper-locations: com/lhsz/bandian/*/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

